"""Build promptfoo tests from the Project 1 golden dataset (eval/questions.yaml).

One source of truth: edit eval/questions.yaml, then run this script again.
"""
import json
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
QUESTIONS = yaml.safe_load((HERE.parent / "eval" / "questions.yaml").read_text(encoding="utf-8"))


def security_assert(forbidden):
    """Fails if any source used comes from a forbidden document. Fails safely if sources are missing."""
    return {"type": "javascript", "value": (
        "const md = context.providerResponse && context.providerResponse.metadata;\n"
        "if (!md) return { pass: false, score: 0, reason: 'no provider metadata available' };\n"
        f"const forbidden = {json.dumps(forbidden)};\n"
        "const leaked = md.sources.filter(s => forbidden.includes(s));\n"
        "return { pass: leaked.length === 0, score: leaked.length === 0 ? 1 : 0,\n"
        "         reason: leaked.length ? 'PERMISSION LEAK: ' + leaked.join(', ') : 'no forbidden sources' };"
    )}


tests = []
for q in QUESTIONS:
    if q.get("forbidden_sources"):
        checks = [security_assert(q["forbidden_sources"])]
    elif q.get("expect") == "refuse":
        checks = [{"type": "icontains-any", "value": ["couldn't find", "not available"]}]
    else:
        checks = [{"type": "icontains-any", "value": q["must_contain_any"]}]
    tests.append({
        "description": q["id"],
        "vars": {"user": q["user"], "question": q["question"], "category": q.get("category", "other")},
        "assert": checks,
    })

header = "# Generated by build_tests.py from eval/questions.yaml. Do not edit by hand.\n"
(HERE / "tests.yaml").write_text(header + yaml.safe_dump(tests, sort_keys=False, allow_unicode=True),
                                 encoding="utf-8")
print(f"Wrote {len(tests)} tests to regression/tests.yaml")